window.NYC_TRIP={
days:[
{id:'oct3',date:'10/03',dow:'六',title:'調時差＋K-Culture 第一日',area:'LIC → Koreatown / Midtown →（可選）Queens',tone:'easy',core:[['09:30','睡到自然醒、LIC brunch'],['11:00','Gantry Plaza State Park / Hunters Point waterfront，先用低強度行程開場'],['11:45','7 Train 進 Manhattan，前往 Koreatown / 6th Ave'],['12:00–14:00','42nd Korean Parade（6th Ave 38th→27th St）'],['14:00–16:30','Koreatown Festival + 午晚餐，32nd St 一帶'],['17:00 之後','二選一：A. Bryant Park / Times Square 輕鬆收尾；B. 有體力再去 Queens Night Market 18:00–21:00']],food:'Koreatown：韓式烤肉／雪濃湯／炸雞；Queens Night Market 留肚子給國際小吃。',mom:'剛抵達後第一天不要同時硬塞 parade + night market + Times Square；晚上三選一即可。',optional:'Queens Night Market（4pm–midnight）是本週六最值得的季節限定，但如果 jet lag 明顯就放棄。'},
{id:'oct4',date:'10/04',dow:'日',title:'Central Park＋The Met＋5th Avenue',area:'Upper East Side / Midtown',tone:'classic',core:[['09:00','7 Train → Grand Central；可先看主大廳與 Chrysler Building 外觀'],['10:00','Central Park 南側慢走：Gapstow Bridge / The Mall / Bethesda Terrace 擇 2–3 個'],['12:00','午餐＋休息'],['13:30–16:30','The Metropolitan Museum of Art，挑重點館藏不要全逛'],['17:00','5th Ave 往南：St. Patrick’s Cathedral / Rockefeller Center'],['18:00–19:30','Top of the Rock 日落（若選它當唯一觀景台）或直接晚餐']],food:'Upper East Side / Midtown 可安排 deli、bagel、steakhouse 或日式。',mom:'Central Park 不要企圖走完整圈；The Met 也只選 2–3 個 wing。',optional:'若完全不想逛美術館，可把 The Met 換成 Central Park + Roosevelt Island Tram。'},
{id:'oct5',date:'10/05',dow:'一',title:'Statue of Liberty＋Lower Manhattan',area:'Hunters Point → Wall Street / Battery Park',tone:'must',core:[['08:30','若 ferry 時刻合適，從 Hunters Point South 搭 NYC Ferry 看 skyline 到 Wall St / Pier 11'],['09:30–13:30','Battery Park → Statue of Liberty / Ellis Island（需預約官方 ferry）'],['14:00','Stone Street / Financial District 午餐'],['15:00','Wall Street / Charging Bull / Trinity Church'],['16:00–18:00','9/11 Memorial；是否進 Museum 看體力與興趣'],['18:30','Oculus / Brookfield Place，晚餐後回 LIC']],food:'Stone Street、Eataly Downtown 或 Chinatown 晚餐。',mom:'這天戶外多，若下雨就縮短 Statue 行程，改 9/11 Museum＋Oculus。',optional:'想少走路：不走 Brooklyn Bridge，把橋留到 10/7 DUMBO 日。'},
{id:'oct6',date:'10/06',dow:'二',title:'High Line＋Chelsea＋Hudson Yards',area:'West Side',tone:'walk',core:[['09:30','Chelsea / Meatpacking 開始'],['10:00','High Line 北走；沿途坐下休息，不必每個觀景點都停'],['12:00','Chelsea Market 午餐'],['13:30','Little Island 或 Whitney（擇一）'],['15:30','Hudson Yards / Vessel 外觀 / 商場休息'],['17:30','Edge 日落（若選 Edge 當唯一觀景台）'],['19:00','Greenwich Village / West Village 晚餐']],food:'Chelsea Market、West Village 義式／pizza。',mom:'這天步行量高；若媽媽累，Little Island 與 Greenwich Village 可刪掉一個。',optional:'雨天版本：Whitney → Chelsea Market → Hudson Yards 商場 → Edge。'},
{id:'oct7',date:'10/07',dow:'三',title:'Brooklyn 經典日',area:'DUMBO / Brooklyn Heights / Williamsburg',tone:'scenic',core:[['09:30','NYC Ferry 或地鐵前往 DUMBO'],['10:00','Brooklyn Bridge Park + Pebble Beach + Manhattan Bridge 經典視角'],['12:00','Time Out Market / DUMBO 午餐'],['13:30','Brooklyn Heights Promenade'],['15:00','看體力：走 Brooklyn Bridge 回 Manhattan，或搭 ferry / subway'],['17:00','SoHo / Chinatown 晚餐，或直接回 LIC 休息']],food:'DUMBO pizza、Chinatown 港式／中餐。',mom:'Brooklyn Bridge 想走就從 Brooklyn 往 Manhattan 方向，景觀更直覺；累了完全可以不走。',optional:'如果想更 local，把下午改成 Williamsburg waterfront + cafe。'},
{id:'oct8',date:'10/08',dow:'四',title:'Special Event Day：NYCC 或 MoMA＋Broadway',area:'Javits / Midtown',tone:'choice',core:[['09:30','方案 A（不去 NYCC）：MoMA 2–3 小時'],['12:30','Midtown 午餐'],['14:00','Rockefeller / 5th Ave / Bryant Park 補漏'],['17:30','提早吃晚餐'],['19:00','Broadway show'],['—','方案 B（NYCC）：白天整段換成 Javits Center，晚上不要再排太滿']],food:'Theater District 盡量提早 17:00–17:30 吃，避免趕開演。',mom:'NYCC 人非常多；除非真的有興趣，媽媽同行我更推薦 MoMA＋Broadway。',optional:'SUMMIT One Vanderbilt 可放在 Grand Central 附近，但不要再同時買第二個觀景台。'},
{id:'oct9',date:'10/09',dow:'五',title:'Upper West Side＋NYFF',area:'AMNH / Lincoln Center',tone:'culture',core:[['09:30','American Museum of Natural History（挑主題逛）'],['13:00','Upper West Side 午餐'],['14:30','Lincoln Center / Columbus Circle / Central Park 西南角'],['17:00','休息＋早晚餐'],['18:00 之後','NYFF screening / Closing Night（若買到票）；沒有票則回 Midtown / LIC 輕鬆晚餐']],food:'Upper West Side cafe、Jewish deli、Lincoln Square。',mom:'博物館不要逛到閉館；晚上還有電影時，下午務必留坐著休息的時間。',optional:'完全不看 NYFF：下午改 SoHo / Nolita / Chinatown。'},
{id:'oct10',date:'10/10',dow:'六',title:'Queens 收尾＋深夜班機',area:'Flushing / LIC → JFK',tone:'departure',core:[['09:00','退房；寄放行李（若有 late checkout 更舒服）'],['10:00','7 Train 往 Flushing：Flushing Meadows / Unisphere 擇一＋法拉盛吃東西'],['14:30','回 LIC，最後咖啡 / Gantry waterfront / 採買'],['17:30','早晚餐；確認行李、護照、電子登機資料'],['20:00','取行李、叫車'],['20:30','建議離開 LIC 前往 JFK Terminal 1'],['01:25','10/11 BR31 起飛']],food:'Flushing 中餐／台灣小吃／韓式都很強；最後一餐不要排需久候名店。',mom:'今天不要去 Queens Night Market（雖然有開），時間會太靠近國際線回程。',optional:'若前幾天太累，上午完全留在 LIC 也沒問題；最後一天寧可少一個景點。'}
],
options:[
{name:'Grand Central Terminal',cat:'經典',effort:1,indoor:5,mom:5,note:'離 LIC 超近，最適合當順路景點。'},
{name:'Times Square 夜景',cat:'經典',effort:2,indoor:2,mom:3,note:'第一次紐約值得看一次，30–60 分鐘就夠。'},
{name:'Top of the Rock',cat:'觀景',effort:2,indoor:3,mom:4,note:'最適合看 Empire State + Central Park；三個觀景台只選一個。'},
{name:'SUMMIT One Vanderbilt',cat:'觀景',effort:2,indoor:5,mom:4,note:'在 Grand Central 旁，沉浸式、下雨也好用。'},
{name:'Edge',cat:'觀景',effort:2,indoor:3,mom:4,note:'跟 High Line / Hudson Yards 同日最順。'},
{name:'The Met',cat:'博物館',effort:3,indoor:5,mom:4,note:'世界級館藏，適合 3 小時重點逛。'},
{name:'MoMA',cat:'博物館',effort:2,indoor:5,mom:5,note:'比 Met 更容易控制在 2–3 小時。'},
{name:'AMNH',cat:'博物館',effort:3,indoor:5,mom:4,note:'Upper West Side 文化日很好搭。'},
{name:'9/11 Museum',cat:'博物館',effort:2,indoor:5,mom:5,note:'雨天 Lower Manhattan 最強備案。'},
{name:'Roosevelt Island Tram',cat:'輕鬆',effort:1,indoor:2,mom:5,note:'短時間就有空中景觀，適合補空檔。'},
{name:'Gantry Plaza State Park',cat:'輕鬆',effort:1,indoor:1,mom:5,note:'住處附近免費 skyline，第一／最後一天都好用。'},
{name:'NYC Ferry East River',cat:'輕鬆',effort:1,indoor:3,mom:5,note:'把交通變景點，去 DUMBO / Wall St 特別適合。'},
{name:'Flushing 美食半日',cat:'美食',effort:2,indoor:4,mom:5,note:'7 Train 直達，最後一天很實用。'},
{name:'Queens Night Market',cat:'活動',effort:3,indoor:1,mom:3,note:'10/3 最適合；10/10 不建議因為深夜班機。'},
{name:'Korean Parade & Festival',cat:'活動',effort:2,indoor:1,mom:4,note:'10/3 限定，位置就在 Midtown / Koreatown。'},
{name:'New York Film Festival',cat:'活動',effort:1,indoor:5,mom:5,note:'9/25–10/12；適合 10/9 Lincoln Center 文化日。'},
{name:'New York Comic Con',cat:'活動',effort:4,indoor:5,mom:2,note:'10/8–11；人潮大，只有真的有興趣才換掉一天。'},
{name:'NYBG Día de los Muertos',cat:'秋季',effort:3,indoor:2,mom:4,note:'10/3–11/2；秋天花園＋墨西哥文化，需多一段 Bronx 交通。'},
{name:'Brooklyn Bridge walk',cat:'經典',effort:4,indoor:1,mom:2,note:'可以只在 DUMBO 看橋，不必一定走完整座。'},
{name:'SoHo / Nolita / Chinatown',cat:'美食',effort:3,indoor:2,mom:3,note:'適合用來補 NYFF 沒買票或下半天自由時間。'}
]};
